[package]
name = "eulerst"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.76"
num-traits = "0.2"
num-integer = "0.1"
rayon = { version = "1.7", optional = true }
num-bigint = { version = "0.4.6", features = ["serde"] }

[features]
parallel = ["rayon"]
